name: movie_explorer_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_mlkit_digital_ink_recognition: ^0.14.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  http: ^1.3.0
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  just_audio: ^0.9.34
  go_router: ^14.8.1
  google_mlkit_text_recognition: ^0.15.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

